<template>
  <v-container
    id="subscribe"
    tag="section"
  >
    <base-card
      color="rgba(203, 170, 92, 0.51)"
      class="pa-3"
    >
      <v-container
        grid-list-xl
        pa-0
      >
        <v-layout wrap>
          <v-flex
            xs12
            md5
          >
            <base-subheading class="mb-3">
              Comment
            </base-subheading>
            <p>
              如果碰到了一些问题，你可以在留言面板进行留言，如果你不知道留言面板在哪里，点击下面这个按钮。
            </p>

            <v-layout
              wrap
              pa-2
            >
              <v-btn
                :block="$vuetify.breakpoint.xsOnly"
                class="ma-0"
                color="secondary"
                style="height: 48px"
                router
                to="/comment"
              >
                Comment
              </v-btn>
            </v-layout>
          </v-flex>
          <v-flex
            xs12
            md6
            offset-md1
          >
            <base-subheading>Contact</base-subheading>
            <v-list class="transparent">
              <v-list-item>
                <v-list-item-avatar
                  color="primary"
                >
                  <v-icon
                    class="elevation-4"
                    dark
                  >
                    mdi-email-outline
                  </v-icon>
                </v-list-item-avatar>
                <v-list-item-title>EMAIL</v-list-item-title>
                <v-list-item-subtitle>
                  2230647190@qq.com
                </v-list-item-subtitle>
              </v-list-item>
              <v-list-item>
                <v-list-item-avatar
                  color="primary"
                >
                  <v-icon
                    class="elevation-4"
                    dark
                  >
                    mdi-map-marker
                  </v-icon>
                </v-list-item-avatar>
                <v-list-item-title>ADDRESS</v-list-item-title>
                <v-list-item-subtitle>
                  江苏省南京市浦珠南路 南京工业大学
                </v-list-item-subtitle>
              </v-list-item>
              <v-list-item>
                <v-list-item-avatar
                  color="primary"
                >
                  <v-icon
                    class="elevation-4"
                    dark
                  >
                    mdi-phone
                  </v-icon>
                </v-list-item-avatar>
                <v-list-item-title>PHONE</v-list-item-title>
                <v-list-item-subtitle>
                   025 - a secret
                </v-list-item-subtitle>
              </v-list-item>
            </v-list>
          </v-flex>
        </v-layout>
      </v-container>
    </base-card>
  </v-container>
</template>
